import type { Express } from "express";
import { env } from "../config/env.js";
import { prisma } from "../db/prisma.js";
import { asyncHandler } from "../middleware/asyncHandler.js";

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderStatusPage(opts: {
  dbOk: boolean;
  dbDetail: string | null;
}): string {
  const dbLine = opts.dbOk
    ? "<strong>Database</strong>: connected"
    : `<strong>Database</strong>: <span style="color:#b91c1c">not reachable</span> — ${escapeHtml(opts.dbDetail ?? "unknown error")}`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>RFID middleware — status</title>
</head>
<body style="font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;max-width:42rem;margin:2rem auto;padding:0 1rem;line-height:1.5;color:#0f172a;background:#f8fafc">
<h1 style="font-size:1.5rem;margin:0 0 0.5rem">RFID jewelry middleware</h1>
<p style="margin:0 0 1rem;color:#475569;font-size:0.95rem">Server is running. This page is generated by the API (no client JavaScript).</p>
<section style="background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:1rem 1.25rem;margin-bottom:1.25rem;box-shadow:0 1px 2px rgba(15,23,42,0.06)">
<p style="margin:0.35rem 0">${dbLine}</p>
<p style="margin:0.35rem 0"><strong>Environment</strong>: ${escapeHtml(env.NODE_ENV)}</p>
<p style="margin:0.35rem 0"><strong>Time (UTC)</strong>: ${escapeHtml(new Date().toISOString())}</p>
</section>
<section>
<h2 style="font-size:1rem;margin:0 0 0.5rem">JSON endpoints</h2>
<ul style="margin:0;padding-left:1.25rem">
<li><a href="/api/health">GET /api/health</a> — database ping</li>
<li><a href="/api/inventory/summary">GET /api/inventory/summary</a> — inventory summary</li>
</ul>
</section>
<p style="margin-top:1.5rem;font-size:0.875rem;color:#64748b">Use the mobile app or an API client for audit and transfer operations.</p>
</body>
</html>`;
}

export function registerStatusPage(app: Express): void {
  app.get(
    "/status",
    asyncHandler(async (_req, res) => {
      let dbOk = false;
      let dbDetail: string | null = null;
      try {
        await prisma.$queryRaw`SELECT 1`;
        dbOk = true;
      } catch (e) {
        dbDetail = e instanceof Error ? e.message : String(e);
      }
      res.type("html").send(renderStatusPage({ dbOk, dbDetail }));
    }),
  );

  app.get("/", (_req, res) => {
    res.redirect(302, "/status");
  });
}
